auth-server: http://localhost:8081/uaa
server:
  port: 9091
  contextPath: /notifications
logging:
  file: c://mbalusu/notifications.log
feign:
#  oauth2:
#    enabled: true
  hystrix:
    enabled: false
hystrix.command.default.execution.isolation.strategy: SEMAPHORE
security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      clientId: my-trusted-client
#      clientSecret: secret
#      accessTokenUri: ${auth-server}/oauth/token
#      userAuthorizationUri: ${auth-server}/oauth/authorize
#      scope: read, write
#    resource:
#      jwt:
#        keyUri: ${auth-server}/oauth/token_key
#resourceServerClient:
#  clientId: my-trusted-client
#  clientSecret: secret
#  accessTokenUri: ${auth-server}/oauth/token
#  userAuthorizationUri: ${auth-server}/oauth/authorize
#  scope: read, write
spring:
    mail:
       host: smtp.gmail.com
       port: 587
       username: mbalusu@gmail.com      
       password: m@!AUG09
       properties.mail.smtp:
                 auth: true
                 starttls.enable: true