eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: /registry/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5