server:
  port: 8090
  contextPath: /ooba
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
ooba:
  provider: GAUTH
  otp:
    delivery:
      preference: BOTH
    redelivery_required: 10
    expiry_minutes: 5
    length: 6
  host:
    name: SWAPSTECH
    url: http://swapstech.com