server:
  port: 8084
  contextPath: /ooba
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
feign:
  hystrix:
    enabled: true

ooba:
  provider: STAR
  otp:
    delivery:
      preference: BOTH
    redelivery_required: 10
    expiry_minutes: 5
    length: 6
  host:
    name: SWAPSTECH
    url: http://swapstech.com
    
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyUri: http://Microservices-lb-1314641267.us-east-2.elb.amazonaws.com/auth/oauth/token_key
config:
    oauth2:
        clientID: service-account-1
        clientSecret: service-account-1-secret
        accessTokenUri: http://Microservices-lb-1314641267.us-east-2.elb.amazonaws.com/auth/oauth/token
        userAuthorizationUri: http://Microservices-lb-1314641267.us-east-2.elb.amazonaws.com/auth/oauth/authorize
        resourceURI: http://Microservices-lb-1314641267.us-east-2.elb.amazonaws.com/ooba/ui