server:
  port: 8090
  contextPath: /ooba
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

security:
  basic:
    enabled: false
    
feign:
  hystrix:
    enabled: true

ooba:
  provider: STAR
  otp:
    delivery:
      preference: BOTH
    redelivery_required: 10
    expiry_minutes: 5
    length: 6
  host:
    name: SWAPSTECH
    url: http://swapstech.com